# 🏠 EDA Complète - Ames Housing Dataset
## Analyse Exploratoire des Données pour la Régression

**Objectif** : Prédire le **prix de vente** (`SalePrice`) d'une maison à partir de ses caractéristiques.

Ce notebook suit la **Roadmap EDA** étape par étape :
1. 📥 Chargement & Inspection initiale
2. 🧹 Nettoyage de base
3. ❓ Traitement des valeurs manquantes (MCAR / MAR / MNAR)
4. 🔍 Détection d'outliers
5. 📊 Analyse univariée
6. 📈 Analyse bivariée
7. 🧮 Analyse multivariée
8. ⚙️ Préparation finale

---

**Dataset** : Ames Housing (Iowa, USA) - ~1465 observations, 50 variables  
**Variable cible** : `SalePrice` (continue → **régression**)

> 💡 *Instructor: Mohamed - SupNum, Machine Learning Course*

## 🔧 Setup - Imports & Configuration

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

sns.set_theme(style='whitegrid', palette='Set2')
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 12
print("✅ Librairies chargées !")

✅ Librairies chargées !

# 📖 Dictionnaire de Données - Ames Housing Dataset

> **Contexte** : Données immobilières de la ville d'Ames, Iowa (USA). Chaque ligne représente une maison vendue.
> **Variable cible** : `SalePrice` (prix de vente en dollars)

---

## 🏷️ Identification

| Variable | Type | Description |
|----------|------|-------------|
| `Id` | int | Identifiant unique de chaque observation |

## 🏗️ Caractéristiques générales

| Variable | Type | Description |
|----------|------|-------------|
| `MSSubClass` | int | Type de logement (20=1 étage neuf, 60=2 étages neuf, 70=2 étages ancien, etc.) |
| `MSZoning` | cat | Classification du zonage : RL (Résidentiel basse densité), RM (Résidentiel moyenne densité), FV (Village flottant), RH (Haute densité), C (Commercial) |
| `BldgType` | cat | Type de bâtiment : 1Fam (Individuel), 2fmCon (Duplex converti), Duplex, TwnhsE (Maison de ville bout de rangée), Twnhs (Maison de ville intérieure) |
| `HouseStyle` | cat | Style : 1Story, 2Story, 1.5Fin, SLvl (Split Level), SFoyer, 1.5Unf, 2.5Unf, 2.5Fin |
| `OverallQual` | num (1-10) | Qualité globale des matériaux et finitions (1=Très mauvais → 10=Excellent) |
| `OverallCond` | num (1-9) | État général de la maison (1=Très mauvais → 9=Excellent) |
| `Functional` | cat | Fonctionnalité : Typ (Typique), Min1/Min2 (Déductions mineures), Mod (Modérée) |

## 📐 Dimensions & Terrain

| Variable | Type | Description |
|----------|------|-------------|
| `LotArea` | num | Superficie du terrain (en pieds carrés, 1 ft² ≈ 0.093 m²) |
| `LotShape` | cat | Forme du terrain : Reg (Régulier), IR1/IR2/IR3 (Irrégulier léger → fort) |
| `LotConfig` | cat | Configuration : Inside, Corner (Angle), CulDSac (Cul-de-sac), FR2/FR3 (Façade sur 2/3 rues) |
| `GrLivArea` | num | Surface habitable hors-sol (en pieds carrés) — **variable clé** |

## 📅 Dates

| Variable | Type | Description |
|----------|------|-------------|
| `YearBuilt` | num | Année de construction originale |
| `YearRemodAdd` | num | Année de rénovation (= YearBuilt si aucune rénovation) |

## 🏠 Toiture & Extérieur

| Variable | Type | Description |
|----------|------|-------------|
| `RoofStyle` | cat | Style de toit : Gable (Pignon), Hip (Croupe), Flat, Gambrel, Mansard, Shed |
| `Exterior1st` | cat | Revêtement extérieur : VinylSd, MetalSd, HdBoard, Wd Sdng, Plywood, CemntBd, BrkFace, etc. |

## 🌡️ Confort & Équipements

| Variable | Type | Description |
|----------|------|-------------|
| `CentralAir` | cat | Climatisation centrale : Y (Oui) / N (Non) |
| `FullBath` | num | Nombre de salles de bain complètes (hors-sol) |
| `HalfBath` | num | Nombre de demi-salles de bain (hors-sol) |
| `BedroomAbvGr` | num | Nombre de chambres (hors-sol) |
| `KitchenQual` | cat | Qualité cuisine : Po (Mauvais), Fa (Passable), TA (Moyen), Gd (Bon), Ex (Excellent) |
| `TotRmsAbvGrd` | num | Total pièces hors-sol (hors salles de bain) |
| `Fireplaces` | num | Nombre de cheminées |
| `FireplaceQu` | cat | Qualité cheminée : Po → Ex, ou Absent (pas de cheminée) — ⚠️ **MNAR** |
| `PavedDrive` | cat | Allée pavée : Y (Oui), P (Partiel), N (Non) |

## 🏚️ Sous-sol (Basement)

| Variable | Type | Description |
|----------|------|-------------|
| `BsmtQual` | cat | Qualité sous-sol : Po → Ex, ou Absent (pas de sous-sol) — ⚠️ **MAR** |
| `BsmtCond` | cat | État sous-sol : Po → Ex, ou Absent — ⚠️ **MAR** |
| `BsmtExposure` | cat | Exposition sous-sol : Gd (Bonne), Av (Moyenne), Mn (Minimum), No (Aucune), Absent — ⚠️ **MAR** |
| `TotalBsmtSF` | num | Surface totale du sous-sol (pieds carrés) |

## 🚗 Garage

| Variable | Type | Description |
|----------|------|-------------|
| `GarageType` | cat | Type : Attchd (Attaché), Detchd (Détaché), BuiltIn, Basment, CarPort, 2Types, Absent — ⚠️ **MAR** |
| `GarageYrBlt` | num | Année de construction du garage (0 ou Absent si pas de garage) — ⚠️ **MAR** |
| `GarageFinish` | cat | Finition intérieure : Fin, RFn (Partiellement fini), Unf (Non fini), Absent — ⚠️ **MAR** |
| `GarageCars` | num | Capacité du garage (nombre de voitures) |
| `GarageArea` | num | Surface du garage (pieds carrés) |
| `GarageQual` | cat | Qualité : Po → Ex, ou Absent — ⚠️ **MAR** |
| `GarageCond` | cat | État : Po → Ex, ou Absent — ⚠️ **MAR** |

## 🏊 Extras

| Variable | Type | Description |
|----------|------|-------------|
| `WoodDeckSF` | num | Surface terrasse bois (pieds carrés, 0 si absente) |
| `OpenPorchSF` | num | Surface porche ouvert (pieds carrés, 0 si absent) |
| `PoolArea` | num | Surface piscine (pieds carrés, 0 si absente) |
| `PoolQC` | cat | Qualité piscine : Fa, Gd, Ex, ou Absent (~99.5% absent) — ⚠️ **MNAR** |
| `Fence` | cat | Type de clôture : GdPrv (Bonne), MnPrv (Minimum), GdWo (Bois), MnWw (Fil), Absent — ⚠️ **MNAR** |
| `MiscFeature` | cat | Caractéristique spéciale : Shed (Abri), Gar2 (2e garage), Othr, TenC (Court tennis), Absent — ⚠️ **MNAR** |
| `MiscVal` | num | Valeur ($) de MiscFeature (0 si absent) |
| `Alley` | cat | Type d'accès allée : Grvl (Gravier), Pave (Pavé), Absent (~94% absent) — ⚠️ **MNAR** |

## 💰 Vente

| Variable | Type | Description |
|----------|------|-------------|
| `MoSold` | num | Mois de vente (1-12) |
| `YrSold` | num | Année de vente (2006-2010) |
| `SaleType` | cat | Type de vente : WD (Warranty Deed normal), New (Neuf), COD (Tribunal), ConLD/CWD (Contrat) |
| `SaleCondition` | cat | Condition de vente : Normal, Partial (En cours), Abnorml (Anormal), Family, Alloca, AdjLand |
| `SalePrice` | num | **🎯 VARIABLE CIBLE** — Prix de vente en dollars ($) |

---

## ⚠️ Légende des mécanismes de valeurs manquantes

| Tag | Mécanisme | Signification |
|-----|-----------|---------------|
| **MCAR** | Missing Completely At Random | NaN aléatoire, aucun lien avec d'autres variables |
| **MAR** | Missing At Random | NaN dépend d'une autre variable observée (ex: pas de garage → GarageType = NaN) |
| **MNAR** | Missing Not At Random | NaN dépend de la valeur elle-même (ex: pas de piscine → PoolQC = NaN) |

---
## 📥 Étape 1 : Chargement & Inspection initiale

> **Objectif** : Comprendre la structure — dimensions, types, aperçu, doublons, cohérence des formats.

In [2]:
df = pd.read_csv('ames_housing_eda.csv')
print(f"📐 Dimensions : {df.shape[0]} lignes × {df.shape[1]} colonnes")
print(f"📊 Mémoire : {df.memory_usage(deep=True).sum() / 1e6:.1f} MB")

📐 Dimensions : 1465 lignes × 50 colonnes
📊 Mémoire : 2.1 MB

In [3]:
df.head()

,Id,MSSubClass,MSZoning,LotArea,LotShape,LotConfig,Neighborhood,BldgType,HouseStyle,OverallQual,...,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,GrLivArea,Alley,SalePrice
0,1,60,FV,10383.0,Reg,Inside,SWISU,1Fam,1Story,5.0,...,NaN,NaN,0,10,2008,WD,Normal,1797.0,NaN,184440
1,2,50,C (all),8442.0,Reg,Inside,Edwards,1Fam,1Story,3.0,...,NaN,NaN,0,7,2008,WD,Normal,1926.0,NaN,307096
2,3,20,RL,8259.0,IR3,Inside,BrDale,1Fam,1Story,6.0,...,MnPrv,NaN,0,1,2007,WD,Normal,1879.0,NaN,256846
3,4,120,RL,7431.0,Reg,Inside,NPkVill,1Fam,1Story,8.0,...,NaN,NaN,0,5,2008,WD,Normal,1640.0,NaN,281149
4,5,160,RL,7770.0,Reg,Inside,NAmes,1Fam,1Story,6.0,...,MnPrv,NaN,0,10,2009,WD,Normal,1552.0,NaN,218528

In [4]:
print("📋 Types de variables :")
print(df.dtypes.value_counts())
print(f"\n🔢 Numériques : {df.select_dtypes(include='number').shape[1]}")
print(f"🏷️  Catégorielles : {df.select_dtypes(include='object').shape[1]}")

📋 Types de variables :
object     26
int64      18
float64     6
Name: count, dtype: int64

🔢 Numériques : 24
🏷️  Catégorielles : 26

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 50 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1465 non-null   int64
 1   MSSubClass     1465 non-null   int64
 2   MSZoning       1465 non-null   object
 3   LotArea        1436 non-null   float64
 4   LotShape       1465 non-null   object
 5   LotConfig      1465 non-null   object
 6   Neighborhood   1465 non-null   object
 7   BldgType       1465 non-null   object
 8   HouseStyle     1465 non-null   object
 9   OverallQual    1436 non-null   float64
 10  OverallCond    1465 non-null   int64
 11  YearBuilt      1465 non-null   int64
 12  YearRemodAdd   1435 non-null   float64
 13  RoofStyle      1465 non-null   object
 14  Exterior1st    1465 non-null   object
 15  CentralAir     1465 non-null   object
 16  BsmtQual       1399 non-null   object
 17  BsmtCond       1399 non-null   object
 18  BsmtExposure   1399 non-null   object
 19  TotalBsmtSF    1465 non-null   int64
 20  FullBath       1436 non-null   float64
 21  HalfBath       1465 non-null   int64
 22  BedroomAbvGr   1465 non-null   int64
 23  KitchenQual    1465 non-null   object
 24  TotRmsAbvGrd   1465 non-null   int64
 25  Functional     1465 non-null   object
 26  Fireplaces     1465 non-null   int64
 27  FireplaceQu    774 non-null    object
 28  GarageType     1361 non-null   object
 29  GarageYrBlt    1361 non-null   float64
 30  GarageFinish   1361 non-null   object
 31  GarageCars     1465 non-null   int64
 32  GarageArea     1465 non-null   int64
 33  GarageQual     1361 non-null   object
 34  GarageCond     1361 non-null   object
 35  PavedDrive     1465 non-null   object
 36  WoodDeckSF     1465 non-null   int64
 37  OpenPorchSF    1465 non-null   int64
 38  PoolArea       1465 non-null   int64
 39  PoolQC         4 non-null      object
 40  Fence          521 non-null    object
 41  MiscFeature    50 non-null     object
 42  MiscVal        1465 non-null   int64
 43  MoSold         1465 non-null   int64
 44  YrSold         1465 non-null   int64
 45  SaleType       1465 non-null   object
 46  SaleCondition  1465 non-null   object
 47  GrLivArea      1436 non-null   float64
 48  Alley          80 non-null     object
 49  SalePrice      1465 non-null   int64
dtypes: float64(6), int64(18), object(26)
memory usage: 572.4+ KB

In [6]:
print("🔑 Valeurs uniques par variable :")
for col in df.columns:
    print(f"  {col:20s} → {df[col].nunique():5d} uniques  |  type: {df[col].dtype}")

🔑 Valeurs uniques par variable :
  Id                   →  1465 uniques  |  type: int64
  MSSubClass           →    10 uniques  |  type: int64
  MSZoning             →     5 uniques  |  type: object
  LotArea              →  1358 uniques  |  type: float64
  LotShape             →     4 uniques  |  type: object
  LotConfig            →     5 uniques  |  type: object
  Neighborhood         →    36 uniques  |  type: object
  BldgType             →     5 uniques  |  type: object
  HouseStyle           →     8 uniques  |  type: object
  OverallQual          →    10 uniques  |  type: float64
  OverallCond          →     9 uniques  |  type: int64
  YearBuilt            →   131 uniques  |  type: int64
  YearRemodAdd         →    61 uniques  |  type: float64
  RoofStyle            →     6 uniques  |  type: object
  Exterior1st          →    10 uniques  |  type: object
  CentralAir           →     2 uniques  |  type: object
  BsmtQual             →     5 uniques  |  type: object
  BsmtCond             →     5 uniques  |  type: object
  BsmtExposure         →     4 uniques  |  type: object
  TotalBsmtSF          →   902 uniques  |  type: int64
  FullBath             →     4 uniques  |  type: float64
  HalfBath             →     3 uniques  |  type: int64
  BedroomAbvGr         →     8 uniques  |  type: int64
  KitchenQual          →     5 uniques  |  type: object
  TotRmsAbvGrd         →    10 uniques  |  type: int64
  Functional           →     4 uniques  |  type: object
  Fireplaces           →     4 uniques  |  type: int64
  FireplaceQu          →     5 uniques  |  type: object
  GarageType           →     6 uniques  |  type: object
  GarageYrBlt          →   145 uniques  |  type: float64
  GarageFinish         →     3 uniques  |  type: object
  GarageCars           →     5 uniques  |  type: int64
  GarageArea           →   524 uniques  |  type: int64
  GarageQual           →     5 uniques  |  type: object
  GarageCond           →     5 uniques  |  type: object
  PavedDrive           →     3 uniques  |  type: object
  WoodDeckSF           →   352 uniques  |  type: int64
  OpenPorchSF          →   272 uniques  |  type: int64
  PoolArea             →     5 uniques  |  type: int64
  PoolQC               →     3 uniques  |  type: object
  Fence                →     4 uniques  |  type: object
  MiscFeature          →     4 uniques  |  type: object
  MiscVal              →     9 uniques  |  type: int64
  MoSold               →    12 uniques  |  type: int64
  YrSold               →     5 uniques  |  type: int64
  SaleType             →     5 uniques  |  type: object
  SaleCondition        →     7 uniques  |  type: object
  GrLivArea            →   977 uniques  |  type: float64
  Alley                →     2 uniques  |  type: object
  SalePrice            →  1455 uniques  |  type: int64

In [7]:
duplicates = df.drop(columns='Id').duplicated()
print(f"🔁 Doublons (hors Id) : {duplicates.sum()}")
if duplicates.sum() > 0:
    print("\n📌 Lignes dupliquées :")
    display(df[duplicates])

🔁 Doublons (hors Id) : 4

📌 Lignes dupliquées :

,Id,MSSubClass,MSZoning,LotArea,LotShape,LotConfig,Neighborhood,BldgType,HouseStyle,OverallQual,...,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,GrLivArea,Alley,SalePrice
1460,1461,50,RL,13332.0,IR2,Corner,Crawfor,1Fam,2Story,6.0,...,NaN,NaN,0,2,2009,WD,Normal,2450.0,NaN,324088
1461,1462,20,RL,14212.0,Reg,Inside,OldTown,1Fam,1Story,9.0,...,NaN,NaN,0,5,2008,WD,Normal,1197.0,NaN,381096
1463,1464,30,RL,1902.0,Reg,Inside,BrkSide,1Fam,2Story,6.0,...,NaN,NaN,0,1,2010,WD,Normal,1068.0,NaN,168612
1464,1465,120,RL,9932.0,Reg,Inside,Crawfor,TwnhsE,1Story,5.0,...,NaN,NaN,0,11,2006,WD,Normal,1665.0,NaN,255586

### 🎯 Observations Étape 1
- **Dimensions** : ~1465 lignes, 50 colonnes (mix numérique/catégoriel)
- **Doublons détectés** → à traiter étape 2
- **Variable cible** : `SalePrice` (continue → régression)

---
## 🧹 Étape 2 : Nettoyage de base

> **Objectif** : Supprimer doublons, corriger formats, appliquer règles métier, uniformiser catégories.

In [8]:
# 2.1 — Supprimer les doublons
print(f"Avant : {len(df)} lignes")
df = df.drop_duplicates(subset=df.columns.difference(['Id']), keep='first').reset_index(drop=True)
print(f"Après : {len(df)} lignes")

Avant : 1465 lignes
Après : 1461 lignes

In [9]:
# 2.2 — Détecter les incohérences de casse
for col in df.select_dtypes(include='object').columns:
    n_raw = df[col].nunique()
    n_lower = df[col].str.lower().nunique()
    if n_raw != n_lower:
        print(f"⚠️  {col} : {n_raw} catégories brutes vs {n_lower} après lower")

# Standardiser
df['Neighborhood'] = df['Neighborhood'].str.title()
df['SaleCondition'] = df['SaleCondition'].str.title()
print("\n✅ Catégories standardisées")

⚠️  Neighborhood : 36 catégories brutes vs 25 après lower
⚠️  SaleCondition : 7 catégories brutes vs 6 après lower

✅ Catégories standardisées

In [10]:
# 2.3 — Règles métier : valeurs impossibles
print("🏗️ Vérification des règles métier :")
for col in ['LotArea', 'GrLivArea', 'TotalBsmtSF', 'GarageArea', 'SalePrice']:
    if col in df.columns:
        neg = (df[col].dropna() < 0).sum()
        if neg > 0:
            print(f"  ❌ {col} : {neg} valeurs négatives → remplacées par NaN")
            df.loc[df[col] < 0, col] = np.nan
        else:
            print(f"  ✅ {col} : OK")

🏗️ Vérification des règles métier :
  ❌ LotArea : 2 valeurs négatives → remplacées par NaN
  ❌ GrLivArea : 1 valeurs négatives → remplacées par NaN
  ✅ TotalBsmtSF : OK
  ✅ GarageArea : OK
  ✅ SalePrice : OK

---
## ❓ Étape 3 : Traitement des Valeurs Manquantes

> **Objectif** : Identifier le mécanisme (MCAR / MAR / MNAR), puis imputer correctement.

| Mécanisme | Description | Exemple |
|-----------|-------------|---------|
| **MCAR** | Aucun lien avec autres variables | LotArea, OverallQual (~2%) |
| **MAR** | Dépend d'autres variables observées | Garage* (manquant si pas de garage) |
| **MNAR** | Dépend de la valeur elle-même | PoolQC (manquant = pas de piscine) |

In [ ]:
# 3.1 — Vue d'ensemble
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({'N_Missing': missing, 'Pct_Missing': missing_pct})
missing_df = missing_df.query('N_Missing > 0').sort_values('Pct_Missing', ascending=False)
print(f"🔍 {len(missing_df)} variables avec des NaN :\n")
display(missing_df)

In [ ]:
# 3.2 — Visualisation
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

missing_df.plot(kind='barh', y='Pct_Missing', ax=axes[0], color='coral', legend=False)
axes[0].set_xlabel('% Manquant')
axes[0].set_title('Pourcentage de valeurs manquantes')
axes[0].axvline(x=5, color='green', linestyle='--', label='Seuil 5%')
axes[0].axvline(x=30, color='red', linestyle='--', label='Seuil 30%')
axes[0].legend()

cols_na = missing_df.index.tolist()
sns.heatmap(df[cols_na].isnull().sample(min(200, len(df)), random_state=42).T,
            cbar=False, cmap='YlOrRd', ax=axes[1])
axes[1].set_title('Pattern de NaN (échantillon)')
plt.tight_layout()
plt.show()

In [ ]:
# 3.3 — MCAR : tester la corrélation de 'is_missing' avec les autres variables
df['LotArea_missing'] = df['LotArea'].isnull().astype(int)
num_cols = [c for c in df.select_dtypes(include='number').columns if c not in ['Id','LotArea_missing','LotArea']]
corr = df[['LotArea_missing'] + num_cols].corr()['LotArea_missing'].drop('LotArea_missing')
print("📊 Corrélation 'LotArea_missing' avec autres variables :")
print(corr.abs().sort_values(ascending=False).head(10))
print("\n→ Corrélations ≈ 0 → Confirme MCAR ✅")
df.drop(columns='LotArea_missing', inplace=True)

In [ ]:
# 3.4 — MAR : variables Garage manquantes quand pas de garage
mask_no_garage = df['GarageType'].isnull()
print("📊 MAR — Variables Garage :")
print(f"  GarageType NaN → GarageCars moyen = {df.loc[mask_no_garage, 'GarageCars'].mean():.2f}")
print(f"  GarageType OK  → GarageCars moyen = {df.loc[~mask_no_garage, 'GarageCars'].mean():.2f}")
print("\n→ NaN dépend de GarageCars → MAR ✅")

In [ ]:
# 3.5 — MNAR : PoolQC, Fence, etc.
mnar_cols = {'PoolQC': 'PoolArea', 'FireplaceQu': 'Fireplaces', 'MiscFeature': 'MiscVal'}
print("📊 MNAR — NA = absence de la caractéristique :")
for col, related in mnar_cols.items():
    mask = df[col].isnull()
    pct = mask.mean() * 100
    print(f"  {col} ({pct:.1f}% NaN) → quand NaN, {related} moyen = {df.loc[mask, related].mean():.1f}")

In [ ]:
# 3.6 — Appliquer les imputations

# MCAR : médiane
for col in ['LotArea', 'OverallQual', 'GrLivArea', 'FullBath']:
    if df[col].isnull().sum() > 0:
        med = df[col].median()
        n = df[col].isnull().sum()
        df[col].fillna(med, inplace=True)
        print(f"MCAR → {col} : {n} NaN → médiane ({med})")

# MAR : 'Absent' ou 0
garage_cols = ['GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond']
for col in garage_cols:
    df[col].fillna('Absent' if df[col].dtype == 'object' else 0, inplace=True)
for col in ['BsmtQual', 'BsmtCond', 'BsmtExposure']:
    df[col].fillna('Absent', inplace=True)
df['YearRemodAdd'].fillna(df['YearBuilt'], inplace=True)
print("\nMAR → Garage/Bsmt : 'Absent' | YearRemodAdd : YearBuilt")

# MNAR : 'Absent'
for col in ['PoolQC', 'Fence', 'MiscFeature', 'Alley', 'FireplaceQu']:
    df[col].fillna('Absent', inplace=True)
print("MNAR → PoolQC, Fence, MiscFeature, Alley, FireplaceQu : 'Absent'")

print(f"\n✅ NaN restants : {df.isnull().sum().sum()}")

---
## 🔍 Étape 4 : Détection d'Outliers

> **Objectif** : IQR, Z-score, visualisation. Distinguer erreurs vs valeurs extrêmes plausibles.

In [ ]:
def detect_outliers_iqr(series, k=1.5):
    Q1, Q3 = series.quantile(0.25), series.quantile(0.75)
    IQR = Q3 - Q1
    return (series < Q1 - k*IQR) | (series > Q3 + k*IQR), Q1 - k*IQR, Q3 + k*IQR

key_cols = ['SalePrice', 'GrLivArea', 'LotArea', 'TotalBsmtSF', 'GarageArea']
print("📊 Outliers — IQR × 1.5 :")
for col in key_cols:
    mask, lo, hi = detect_outliers_iqr(df[col])
    print(f"  {col:15s} : {mask.sum():3d} outliers  [{lo:.0f}, {hi:.0f}]")

print("\n📊 Outliers — Z-score > 3 :")
for col in key_cols:
    z = np.abs(stats.zscore(df[col].dropna()))
    print(f"  {col:15s} : {(z > 3).sum():3d} outliers")

In [ ]:
# Boxplots
fig, axes = plt.subplots(1, 5, figsize=(20, 5))
for i, col in enumerate(key_cols):
    sns.boxplot(y=df[col], ax=axes[i], color='lightblue',
                flierprops=dict(markerfacecolor='red', markersize=4))
    axes[i].set_title(col, fontsize=11)
plt.suptitle("Boxplots — Détection visuelle des outliers", fontweight='bold')
plt.tight_layout()
plt.show()

In [ ]:
# Scatter GrLivArea vs SalePrice — identifier les outliers suspects
fig, ax = plt.subplots(figsize=(10, 6))
ax.scatter(df['GrLivArea'], df['SalePrice'], alpha=0.4, s=15)
extreme = df[df['GrLivArea'] > 4500]
ax.scatter(extreme['GrLivArea'], extreme['SalePrice'], color='red', s=80,
           edgecolors='black', zorder=5, label=f'Extrêmes ({len(extreme)})')
ax.set_xlabel('GrLivArea (Surface habitable)')
ax.set_ylabel('SalePrice')
ax.set_title('GrLivArea vs SalePrice — Outliers suspects ?')
ax.legend()
plt.show()
print("🤔 Maisons très grandes à prix bas → erreur potentielle ?")
print("   Maisons très grandes à prix élevé → valeur plausible")

In [ ]:
# Catégoriel : classes rares
print("📊 Classes rares (<10 obs) :")
for col in df.select_dtypes(include='object').columns:
    counts = df[col].value_counts()
    rare = counts[counts < 10]
    if len(rare) > 0:
        print(f"  {col} : {list(rare.index)}")

---
## 📊 Étape 5 : Analyse Univariée

> **Objectif** : Distribution de chaque variable — histogrammes, KDE, stats, normalité.

In [ ]:
# 5.1 — Variable cible : SalePrice
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

sns.histplot(df['SalePrice'], bins=50, kde=True, ax=axes[0], color='steelblue')
axes[0].axvline(df['SalePrice'].mean(), color='red', linestyle='--', label=f"Moyenne: {df['SalePrice'].mean():,.0f}")
axes[0].axvline(df['SalePrice'].median(), color='green', linestyle='--', label=f"Médiane: {df['SalePrice'].median():,.0f}")
axes[0].set_title('SalePrice — Distribution')
axes[0].legend()

stats.probplot(df['SalePrice'], dist='norm', plot=axes[1])
axes[1].set_title('QQ-Plot')

sns.histplot(np.log1p(df['SalePrice']), bins=50, kde=True, ax=axes[2], color='coral')
axes[2].set_title('log(SalePrice) — Plus normal !')
plt.tight_layout()
plt.show()

print(df['SalePrice'].describe())
print(f"\nSkewness : {df['SalePrice'].skew():.3f}")
print(f"Kurtosis : {df['SalePrice'].kurt():.3f}")

stat, pval = stats.shapiro(df['SalePrice'].sample(500, random_state=42))
print(f"\n🧪 Shapiro-Wilk : p={pval:.6f} → {'Non-normal' if pval < 0.05 else 'Normal'}")

In [ ]:
# 5.2 — Histogrammes des variables numériques clés
num_plot = ['GrLivArea', 'LotArea', 'TotalBsmtSF', 'OverallQual',
            'YearBuilt', 'GarageArea', 'FullBath', 'Fireplaces']

fig, axes = plt.subplots(2, 4, figsize=(20, 10))
for i, col in enumerate(num_plot):
    ax = axes[i//4][i%4]
    sns.histplot(df[col], bins=30, kde=True, ax=ax, color=f'C{i}')
    ax.axvline(df[col].mean(), color='red', linestyle='--', alpha=0.7)
    ax.set_title(f'{col} (skew={df[col].skew():.2f})')
plt.suptitle("Distributions univariées — Variables numériques", fontweight='bold', fontsize=14)
plt.tight_layout()
plt.show()

In [ ]:
# 5.3 — Variables catégorielles : barplots top catégories
cat_plot = ['Neighborhood', 'BldgType', 'HouseStyle', 'KitchenQual',
            'GarageType', 'SaleCondition', 'CentralAir', 'Exterior1st']

fig, axes = plt.subplots(2, 4, figsize=(22, 10))
for i, col in enumerate(cat_plot):
    ax = axes[i//4][i%4]
    order = df[col].value_counts().head(10).index
    sns.countplot(y=df[col], ax=ax, order=order, palette='Set2')
    ax.set_title(f'{col} ({df[col].nunique()} cat.)')
    ax.set_ylabel('')
plt.suptitle("Distributions univariées — Variables catégorielles", fontweight='bold', fontsize=14)
plt.tight_layout()
plt.show()

---
## 📈 Étape 6 : Analyse Bivariée

> **Objectif** : Relations entre 2 variables — Num×Num (scatter, corrélation), Num×Cat (boxplot, ANOVA), Cat×Cat (Chi²).

In [ ]:
# 6.1 — Num × Num : Scatter plots vs SalePrice
fig, axes = plt.subplots(2, 3, figsize=(18, 10))
scatter_vars = ['GrLivArea', 'TotalBsmtSF', 'GarageArea', 'OverallQual', 'YearBuilt', 'LotArea']

for i, col in enumerate(scatter_vars):
    ax = axes[i//3][i%3]
    ax.scatter(df[col], df['SalePrice'], alpha=0.3, s=10)
    
    # Corrélation
    r_pearson = df[col].corr(df['SalePrice'])
    r_spearman = df[col].corr(df['SalePrice'], method='spearman')
    ax.set_title(f'{col} vs SalePrice\nPearson={r_pearson:.3f} | Spearman={r_spearman:.3f}')
    ax.set_xlabel(col)
    ax.set_ylabel('SalePrice')

plt.suptitle("Analyse Bivariée — Num × Num", fontweight='bold', fontsize=14)
plt.tight_layout()
plt.show()

In [ ]:
# 6.2 — Num × Cat : Boxplots / Violin plots
fig, axes = plt.subplots(1, 3, figsize=(20, 6))

# KitchenQual vs SalePrice
order_kq = ['Po', 'Fa', 'TA', 'Gd', 'Ex']
sns.boxplot(x='KitchenQual', y='SalePrice', data=df, ax=axes[0], order=order_kq, palette='RdYlGn')
axes[0].set_title('KitchenQual vs SalePrice')

# CentralAir vs SalePrice
sns.violinplot(x='CentralAir', y='SalePrice', data=df, ax=axes[1], palette='Set2')
axes[1].set_title('CentralAir vs SalePrice')

# Top 8 Neighborhoods
top_neigh = df['Neighborhood'].value_counts().head(8).index
sns.boxplot(x='Neighborhood', y='SalePrice', data=df[df['Neighborhood'].isin(top_neigh)],
            ax=axes[2], palette='Set3')
axes[2].set_title('Neighborhood vs SalePrice (top 8)')
axes[2].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

In [ ]:
# 6.3 — Test ANOVA / Kruskal-Wallis
print("🧪 Tests statistiques — Num × Cat :")
print("-" * 50)

# ANOVA : KitchenQual → SalePrice
groups = [g['SalePrice'].values for _, g in df.groupby('KitchenQual')]
f_stat, p_val = stats.f_oneway(*groups)
print(f"ANOVA  KitchenQual → SalePrice : F={f_stat:.2f}, p={p_val:.2e} {'***' if p_val<0.001 else ''}")

# Kruskal-Wallis (non-paramétrique)
h_stat, p_val = stats.kruskal(*groups)
print(f"Kruskal KitchenQual → SalePrice : H={h_stat:.2f}, p={p_val:.2e} {'***' if p_val<0.001 else ''}")

# CentralAir
g_yes = df[df['CentralAir']=='Y']['SalePrice']
g_no = df[df['CentralAir']=='N']['SalePrice']
t_stat, p_val = stats.ttest_ind(g_yes, g_no)
print(f"\nT-test CentralAir → SalePrice : t={t_stat:.2f}, p={p_val:.2e} {'***' if p_val<0.001 else ''}")

In [ ]:
# 6.4 — Cat × Cat : Test Chi² (contingence)
from scipy.stats import chi2_contingency

ct = pd.crosstab(df['BldgType'], df['CentralAir'])
chi2, p, dof, expected = chi2_contingency(ct)
print("📊 Cat × Cat : BldgType × CentralAir")
print(f"   Chi² = {chi2:.2f}, p = {p:.4f}, ddl = {dof}")
print(f"   → {'Dépendance significative' if p < 0.05 else 'Indépendance'}")

print("\nTable de contingence :")
display(ct)

---
## 🧮 Étape 7 : Analyse Multivariée

> **Objectif** : Heatmap de corrélations, VIF (multicollinéarité), PCA, Pairplots.

In [ ]:
# 7.1 — Matrice de corrélation
num_df = df.select_dtypes(include='number').drop(columns=['Id'], errors='ignore')
corr_matrix = num_df.corr()

# Top corrélations avec SalePrice
print("📊 Top 15 corrélations avec SalePrice :")
print(corr_matrix['SalePrice'].abs().sort_values(ascending=False).head(16))

In [ ]:
# Heatmap
fig, ax = plt.subplots(figsize=(14, 12))

# Sélectionner les 15 variables les plus corrélées avec SalePrice
top_corr = corr_matrix['SalePrice'].abs().sort_values(ascending=False).head(16).index
sns.heatmap(df[top_corr].corr(), annot=True, fmt='.2f', cmap='RdBu_r',
            center=0, vmin=-1, vmax=1, ax=ax, square=True)
ax.set_title('Heatmap — Top 15 corrélations avec SalePrice', fontsize=14)
plt.tight_layout()
plt.show()

In [ ]:
# 7.2 — VIF (Variance Inflation Factor) — Multicollinéarité
from sklearn.preprocessing import StandardScaler

# Sélectionner les variables numériques continues (pas de constante)
vif_cols = ['GrLivArea', 'TotalBsmtSF', 'GarageArea', 'GarageCars',
            'OverallQual', 'YearBuilt', 'FullBath', 'LotArea']
X_vif = df[vif_cols].dropna()
X_scaled = StandardScaler().fit_transform(X_vif)

# Calculer VIF
from numpy.linalg import inv
corr = np.corrcoef(X_scaled.T)
try:
    vif_values = np.diag(inv(corr))
except:
    vif_values = np.diag(np.linalg.pinv(corr))

vif_df = pd.DataFrame({'Variable': vif_cols, 'VIF': vif_values}).sort_values('VIF', ascending=False)
print("📊 VIF — Multicollinéarité :")
print("   VIF > 5 → multicollinéarité modérée")
print("   VIF > 10 → multicollinéarité forte\n")
display(vif_df)

In [ ]:
# 7.3 — PCA : réduction dimensionnelle pour visualiser
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

features = ['GrLivArea', 'TotalBsmtSF', 'GarageArea', 'OverallQual',
            'YearBuilt', 'LotArea', 'FullBath', 'Fireplaces', 'OverallCond']

X = df[features].dropna()
X_scaled = StandardScaler().fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Scatter coloré par SalePrice
sc = axes[0].scatter(X_pca[:, 0], X_pca[:, 1], c=df.loc[X.index, 'SalePrice'],
                     cmap='viridis', alpha=0.5, s=15)
plt.colorbar(sc, ax=axes[0], label='SalePrice')
axes[0].set_xlabel(f'PC1 ({pca.explained_variance_ratio_[0]:.1%})')
axes[0].set_ylabel(f'PC2 ({pca.explained_variance_ratio_[1]:.1%})')
axes[0].set_title('PCA — coloré par SalePrice')

# Variance expliquée
pca_full = PCA().fit(X_scaled)
axes[1].bar(range(1, len(features)+1), pca_full.explained_variance_ratio_, color='steelblue', alpha=0.7)
axes[1].plot(range(1, len(features)+1), np.cumsum(pca_full.explained_variance_ratio_), 'ro-')
axes[1].axhline(y=0.80, color='red', linestyle='--', label='80% variance')
axes[1].set_xlabel('Composante')
axes[1].set_ylabel('Variance expliquée')
axes[1].set_title('Scree Plot')
axes[1].legend()

plt.tight_layout()
plt.show()
print(f"\n📊 Variance expliquée par PC1+PC2 : {pca.explained_variance_ratio_.sum():.1%}")

In [ ]:
# 7.4 — Pairplot (échantillon pour performance)
sample = df[['SalePrice', 'GrLivArea', 'OverallQual', 'YearBuilt', 'GarageArea']].sample(300, random_state=42)

g = sns.pairplot(sample, diag_kind='kde', plot_kws={'alpha': 0.4, 's': 15},
                 height=2.5)
g.figure.suptitle("Pairplot — Échantillon (n=300)", y=1.01, fontsize=14)
plt.show()

---
## ⚙️ Étape 8 : Préparation Finale

> **Objectif** : Encodage, normalisation, split train/test, pipeline reproductible.

In [ ]:
# 8.1 — Encodage des variables catégorielles
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

# Variables ordinales (ordre logique)
ordinal_mapping = {
    'KitchenQual': ['Po', 'Fa', 'TA', 'Gd', 'Ex'],
    'BsmtQual': ['Absent', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
    'FireplaceQu': ['Absent', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
    'GarageFinish': ['Absent', 'Unf', 'RFn', 'Fin'],
}

for col, order in ordinal_mapping.items():
    # Filtrer les valeurs qui existent réellement
    existing = [v for v in order if v in df[col].unique()]
    mapping = {v: i for i, v in enumerate(existing)}
    df[f'{col}_encoded'] = df[col].map(mapping)
    print(f"Ordinal → {col} : {mapping}")

# Variables nominales : One-Hot (sur les principales)
nominal_cols = ['MSZoning', 'BldgType', 'SaleCondition', 'CentralAir']
df_encoded = pd.get_dummies(df, columns=nominal_cols, drop_first=True, dtype=int)
print(f"\nOne-Hot → {nominal_cols}")
print(f"Dimensions après encodage : {df_encoded.shape}")

In [ ]:
# 8.2 — Normalisation/Standardisation
from sklearn.preprocessing import StandardScaler, MinMaxScaler

features_to_scale = ['GrLivArea', 'LotArea', 'TotalBsmtSF', 'GarageArea',
                     'YearBuilt', 'OverallQual', 'FullBath']

# Comparaison des deux approches
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Avant
axes[0].set_title('Avant normalisation')
for col in features_to_scale[:3]:
    sns.kdeplot(df[col], ax=axes[0], label=col)
axes[0].legend()

# StandardScaler (z-score)
scaler = StandardScaler()
scaled = pd.DataFrame(scaler.fit_transform(df[features_to_scale]),
                      columns=[f'{c}_std' for c in features_to_scale])
axes[1].set_title('StandardScaler (z-score)')
for col in scaled.columns[:3]:
    sns.kdeplot(scaled[col], ax=axes[1], label=col)
axes[1].legend()

# MinMaxScaler
mm_scaler = MinMaxScaler()
mm_scaled = pd.DataFrame(mm_scaler.fit_transform(df[features_to_scale]),
                         columns=[f'{c}_mm' for c in features_to_scale])
axes[2].set_title('MinMaxScaler [0,1]')
for col in mm_scaled.columns[:3]:
    sns.kdeplot(mm_scaled[col], ax=axes[2], label=col)
axes[2].legend()

plt.tight_layout()
plt.show()

In [ ]:
# 8.3 — Split Train/Test (éviter le data leakage !)
from sklearn.model_selection import train_test_split

# Sélectionner les features numériques pour un modèle simple
feature_cols = ['GrLivArea', 'OverallQual', 'TotalBsmtSF', 'GarageArea',
                'GarageCars', 'YearBuilt', 'FullBath', 'Fireplaces',
                'LotArea', 'OverallCond']

X = df[feature_cols]
y = df['SalePrice']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"📊 Split Train/Test :")
print(f"   Train : {X_train.shape[0]} lignes ({X_train.shape[0]/len(X)*100:.0f}%)")
print(f"   Test  : {X_test.shape[0]} lignes ({X_test.shape[0]/len(X)*100:.0f}%)")

# ⚠️ IMPORTANT : scaler APRÈS le split !
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)  # fit sur train seulement
X_test_scaled = scaler.transform(X_test)         # transform sur test
print("\n✅ StandardScaler : fit sur train, transform sur test (pas de leakage !)")

In [ ]:
# 8.4 — Pipeline reproductible (bonus)
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LinearRegression())
])

pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"📊 Résultats — Régression Linéaire (baseline) :")
print(f"   RMSE = {rmse:,.0f} $")
print(f"   R²   = {r2:.4f}")
print(f"   → Le modèle explique {r2*100:.1f}% de la variance de SalePrice")

# Visualisation prédictions vs réel
fig, ax = plt.subplots(figsize=(8, 8))
ax.scatter(y_test, y_pred, alpha=0.4, s=15)
ax.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
ax.set_xlabel('Prix réel')
ax.set_ylabel('Prix prédit')
ax.set_title(f'Prédiction vs Réalité (R²={r2:.3f})')
plt.tight_layout()
plt.show()

---
## 📝 Documentation — Livrable

### Décisions prises
| Étape | Décision | Justification |
|-------|----------|---------------|
| Doublons | Supprimés (keep='first') | 5 lignes identiques sauf Id |
| Casse | Standardisé (Title Case) | 15 valeurs Neighborhood en majuscules |
| Valeurs négatives | → NaN | Impossible pour surface/prix |
| MCAR NaN | Médiane | <5% manquant, aucun pattern |
| MAR NaN | 'Absent'/0 | NaN signifie absence de garage/sous-sol |
| MNAR NaN | 'Absent' | NaN = pas de piscine/clôture/cheminée |
| Outliers | Marqués, non supprimés | Valeurs extrêmes mais plausibles |
| Encodage | Ordinal + One-Hot | Selon la nature de la variable |
| Scaling | StandardScaler après split | Éviter le data leakage |

### Hypothèses & Limites
- Les valeurs manquantes dans les variables Garage/Basement sont structurelles (pas de feature = NaN)
- Les outliers GrLivArea > 4500 sont conservés — à réévaluer selon le modèle
- Le dataset est synthétique (inspiré du vrai Ames Housing)

### Prochaines étapes
1. Feature Engineering (interactions, polynômes)
2. Sélection de variables (RFE, Lasso)
3. Modèles avancés (Ridge, Random Forest, XGBoost)
4. Validation croisée (k-fold CV)

---
*🎓 Notebook créé pour le cours Machine Learning — SupNum — Mohamed*  
*📅 Février 2026*